resolver: nightly-2017-01-31
packages:
- '.'
- location:
    git: "https://github.com/lwm/tasty-discover.git"
    commit: "HEAD"
  extra-dep: true
extra-deps:
- "tasty-th-0.1.4"
flags: {}
extra-package-dbs: []
